### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by jimmykingdennis** [Snailclimb/JavaGuide#2488]
HTML:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Blogging Website</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>
<header>
<h1>Welcome to Our Blogging Website</h1>
</header>
<nav>
<ul>
<li><a href="#">Home</a></li>
<li><a href="#">About</a></li>
<li><a href="#">Contact</a></li>
</ul>
</nav>
<main>
<article>
<h2>Latest Blog Post</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in felis nec justo tincidunt ultricies. Donec nec turpis nec justo tincidunt ultricies.</p>
</article>
<aside>
<h3>Ads</h3>
<p>Advertise here!</p>
</aside>
</main>
<footer>
<p>&copy; 2021 Blogging Website. All rights reserved.</p>
</footer>
</body>
</html>
```

CSS:
```css
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
}

header {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px 0;
}

nav {
    background-color: #444;
    color: #fff;
    text-align: center;
    padding: 10px 0;
}

nav ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
}

nav ul li {
    display: inline;
    margin: 0 10px;
}

nav ul li a {
    color: #fff;
    text-decoration: none;
}

main {
    display: flex;
    justify-content: space-between;
    padding: 20px;
}

article {
    flex: 2;
}

aside {
    flex: 1;
    background-color: #f4f4f4;
    padding: 10px;
}

footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px 0;
}
```
